apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-dotnet-core-example
spec:
  environments:
    - name: dev
      build:
        from: main
    - name: custom-metrics
      build:
        from: custom-metrics
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        ASPNETCORE_URLS: "http://+:8000"
      environmentConfig:
        - environment: custom-metrics
          monitoring: true
