apiVersion: radix.equinor.com/v1
kind: RadixApplication
metadata:
  name: edc2021-radix-app-dotnet-core-example
spec:
  build:
    secrets:
      - SECRET_1
      - SECRET_2
  environments:
    - name: dev
      build:
        from: main
    - name: basic-example
      build:
        from: basic
    # - name: custom-metrics-example
    #   build:
    #     from: custom-metrics
    - name: build-secrets-example
      build:
        from: build-secrets
  components:
    - name: app
      src: ./app
      ports:
        - name: http
          port: 8000
      publicPort: http
      variables:
        ASPNETCORE_URLS: "http://+:8000"
      # environmentConfig:
      #   - environment: custom-metrics-example
      #     monitoring: true
